### ISSUE TITLE
Standard ligatures don't work

### ISSUE THREAD

**Issue by Shaun-Type** [skosch/Crimson#13] opened 2015-02-10 08:33 UTC
I have used old version of Crimson Text and the standard ligatures (fi, ff ...) worked fine. Somehow in the new version (0.8), the standard ligatures won't turn on automatically in InDesign. Is it a bug? Thanks so much.

**Comment by skosch** [comment] 2015-02-11 02:42
It's not a bug, it's a feature :-) When the arm of the f is too long, it makes for nice ligatures with f and l and i, but it's still ugly next to, say, â or ï. So a better solution, if the overall design of the font allows for it, is to shorten the f's arm to get out of the way, which is what I did. As a side effect ligatures aren't really necessary anymore. They should (I think) still be available in the character map though, if you insist on using them. Does that help?

**Comment by Shaun-Type** [comment] 2015-02-11 06:19
I see your point. Now I checked the old version, it indeed has longer arm for the f. However, I have to say, even though the new “f” has shorter arm and won’t be “touching” letters like “i” or “l”, it still creates a rather tight space between them, especially in the smaller point size.

I am using Crimson to set an English book (both print and PDF eBook) with an old fashion feeling to it, so the standard ligatures would be a nice addition to it. However, I can’t just turn on or off standard ligatures anymore and I have to pull them out of the character map manually one by one. And in the PDF version, if people want to copy any words with ligatures, it won’t copy the whole word (ie: “finish” becomes “ nish”) as the ligature “fi” glyph doesn't correspond to “f” and “i”.

I understand it is your choice as the designer. And I do appreciate such high-quality Oldstyle/Garalde font available to public for free. As for the ligatures issue, I have read somewhere that you can have different settings for different languages when you make the font. For example, it would be much nicer to still have the standard ligatures for English. And you can set languages with â or ï automatically turn off the ligatures.

Anyway, thank you very much for creating such beautiful font.

**Comment by adrientetar** [comment] 2015-02-11 06:52
> However, I have to say, even though the new “f” has shorter arm and won’t be “touching” letters like “i” or “l”, it still creates a rather tight space between them, especially in the smaller point size.

Agreed, in a contrasted serif the ligature also gets rid of two close large dots. It is not necessary for a serif like Cambria though.

**Comment by skosch** [comment] 2015-02-11 16:35
I don't disagree at all, I do like me a nice ligature too! There is the option of enabling/disabling ligatures via OpenType features (which I believe is what happens when you click "standard ligatures" in InDesign). If that's not working, then that is indeed a bug that needs fixing. I'm overwhelmed with other work though at the moment, so it may take a while—you're more than welcome to look into it yourself and submit a pull request!

**Comment by adrientetar** [comment] 2015-04-09 07:29
> is to shorten the f's arm to get out of the way

There is still the f.short glyph which is now the default so it seems it's duplicated. IMO it would be nice to have access to the long f, at least as an alternate if not as default. :)

**Comment by katef** [comment] 2015-12-18 02:56
@skosch I'm trying to understand what's going on here. I understand that "fi" should not be a ligature for Roman because that's not neccessary. I think @adrientetar is asking for a long f as a stylistic alt (i.e. by `salt`). I think @Shaun-Type is asking for an fi ligature to be substituted as a non-default option, which would seem to suit providing that by `dlig`. Is that correct?

**Comment by skosch** [comment] 2015-12-18 04:07
Yeah, I think those would fit the bill. Though IIRC the extant ligatures derive from very old outlines and need a facelift, i.e. be constructed afresh from their constituent letters.

**Comment by katef** [comment] 2015-12-18 05:32
Okay. I propose removing substitutions to these ligatures from `liga`, and adding them to `dlig` instead. This applies for the relevant faces only, of course - i.e. Italic should keep fi in `liga` per #18.

Then we can close this issue, and that leaves #23 for re-drawing them.

**Comment by katef** [comment] 2015-12-18 17:35
@Shaun-Type I suppose it's about a year late for your purposes, but ca492c6 should provide what you want; now `liga` is just for things which ought to be present by default (currently we just have `Th` there), and `dlig` is what you'd set for your purposefully old-timey text, to explicitly bring in the `f...` ligatures.

Please re-open if anybody isn't happy with that.

**Closed by katef** 2015-12-18 17:35 UTC
